### PR TITLE
Split helper_functions into several modules under utils

### PR DESCRIPTION
**Pull request by Rodrigo-Tenorio**
May be too much for a single PR, but let's see how this evolves.

### CODE REVIEW

**Comment by Rodrigo-Tenorio** [comment]
- [ ] Restore documentation
- [ ] Use the new function to import matplotlib
- [ ] Test SFT reading
- [ ] Test matplotlib function

**Comment by dbkeitel** [comment]
Had a quick look over the set of submodules so far, and I like it. My only extra suggestion so far would be to put everything PFS-related into a single submodule too, which will then eventually be deprecated and killed wholesale in favour of `snr`.

**Review by dbkeitel — CHANGES_REQUESTED** [review]
Minor fixes, plus can you please post a list of **removed** functions.

**Review by dbkeitel — APPROVED** [review]

**Comment by dbkeitel** [comment]
> Minor fixes, plus can you please post a list of **removed** functions.

--> https://github.com/PyFstat/PyFstat/pull/454#pullrequestreview-1096714513

will merge this now, thanks again!

**Pull request merged**
