### PR TITLE
adopt flake8 linting

### PR DESCRIPTION
**Pull request by dbkeitel**
We've had `flake8` config settings in `setup.cfg` for a while since `black` also uses them, but we have not actually run this linter. Locally I get at the moment:
```
1     E266 too many leading '#' for block comment
1     E722 do not use bare 'except'
1     E731 do not assign a lambda expression, use a def
3     E741 ambiguous variable name 'l'
5     F401 'matplotlib.pyplot as plt' imported but unused
3     F811 redefinition of unused 'outdir' from line 5
28    F821 undefined name 'sampler'
5     F841 local variable 'e' is assigned to but never used
66    W605 invalid escape sequence '\m'
```

### CODE REVIEW

**Comment by dbkeitel** [comment]
[CI output](https://github.com/PyFstat/PyFstat/pull/153/checks?check_run_id=1061853954) for some reason finds 1 issue less (112 instead of 113) but I'll try to reduce that number by 2 orders of magnitude first, before worrying about +-1. ;)

**Comment by dbkeitel** [comment]
I've fixed all the easy ones. Remaining:

1. escape-character warnings from `versioneer.py` - I've just added that one to the ignore list, since fixing such small fry in it will only cause conflicts if there is ever an update to versioneer
1. actual problem to fix in `MCMCFollowUpSearch.run()`:
```
./pyfstat/mcmc_based_searches.py:3109:39: F821 undefined name 'sampler'
./pyfstat/mcmc_based_searches.py:3113:22: F821 undefined name 'sampler'
```
It wasn't immediately clear to me from a first reading of the code what's going on here, it looks simply invalid, but probably it's in reality always defined in the early iterations of the loop before ever hitting that branch. May just need a `None` ininitaliser, but let's have a careful look.
1. **lots** of `undefined name` in `tcw_fstat_map_funcs.py` due to my `_optional_import()` hack which flake8 really doesn't like. I've temporarily added this to ignore as well and will make a reminder issue for a deeper fix.

**Comment by dbkeitel** [comment]
@Rodrigo-Tenorio I've marked this "ready for review" and will put the fix for the remaining `MCMCFollowUpSearch` into a separate PR because I think a slight global cleanup will be a neater solution to that.

**Comment by dbkeitel** [comment]
Rebased on top of #155 and updated README.

**Comment by dbkeitel** [comment]
For the `W605 invalid escape sequence` errors on LaTeX labels, the recommend solution I found was to use `r"strings"`, but as it turns out from running the glicht examples, this actually breaks as soon as `\n` newlines are involved. Need to switch to the more traditional `\\` double-escape solution.

**Review by Rodrigo-Tenorio — APPROVED** [review]

**Comment by dbkeitel** [comment]
> For the `W605 invalid escape sequence` errors on LaTeX labels, the recommend solution I found was to use `r"strings"`, but as it turns out from running the glicht examples, this actually breaks as soon as `\n` newlines are involved. Need to switch to the more traditional `\\` double-escape solution.

Changed to doing this in 84ee9307727f73e38facf56fb2c388b9fba15f2b. All examples now pass.

**Pull request merged**
