### PR TITLE
fix MCMCSearch.plot_prior_posterior()

### PR DESCRIPTION
**Pull request by Rodrigo-Tenorio**
Solve #164, although the initial discussion is in #172 by a silly mistake.

### CODE REVIEW

**Comment by Rodrigo-Tenorio** [comment]
This will be merged after #172 to avoid any mess.

**Review by dbkeitel — DISMISSED** [review]
Rebased and fix confirmed.

**Comment by dbkeitel** [comment]
Added one more commit clarifying the variable names.

**Review by dbkeitel — APPROVED** [review]

**Review by Rodrigo-Tenorio — COMMENTED** [review]
Cleaner solution, I like it!

**Pull request merged**
