### PR TITLE
MCMC: Fix checks when plotting injection parameters

### PR DESCRIPTION
**Pull request by Rodrigo-Tenorio**
If any of the parameters is missing, ignore.
- [x] Plot corner
- [x] Plot prior & posterior
- [x] Chainconsumer
- [x] Walkers

### CODE REVIEW

**Comment by Rodrigo-Tenorio** [comment]
This is the output value whenever any of the injection parameters is missing:
```
15:28 WARNING : plot_corner(): Missing keys {'F0'} in 'truths' dictionary, argument will be ignored.
15:28 WARNING : plot_prior_posterior(): Missing keys {'F0'} in 'truths' dictionary, argument will be ignored.
15:28 WARNING : plot_chainconsumer(): Missing keys ['F0'] in 'truth' dictionary, argument will be ignored.
```

**Comment by Rodrigo-Tenorio** [comment]
However, there's no warning when walker plots fails...

**Comment by dbkeitel** [comment]
> However, there's no warning when walker plots fails...

They're in a global try-except already, because one doesn't want a long and expensive MCMC fail in the end just because it can't plot.

**Comment by Rodrigo-Tenorio** [comment]
That's what I'm seeing... I'll see if I can add a warning

**Comment by Rodrigo-Tenorio** [comment]
```
15:38 WARNING : plot_walkers(): Missing keys {'F0'} in 'injection_parameters', argument will be ignored.
```

**Review by dbkeitel — APPROVED** [review]
Ok, that solution with the overloaded `-` for sets is much simpler than mine with numpy!

**Pull request merged**
