### PR TITLE
Deprecate old MCMCFollowUpSearch and optimal setup functions

### LINKED ISSUE #431: Deprecate follow-up
As a first step towards #333 , current follow-up should probably be preemptively deprecated just to avoid any confusion.

### PR DESCRIPTION
**Pull request by Rodrigo-Tenorio**
First step towards #333 : Make sure there's no confusion and things are not wrongly used by mistake.

- closes #431

### CODE REVIEW

**Review by dbkeitel — COMMENTED** [review]
Not so sure about deprecating the optimal module. I guess those aren't coded up anywhere else, so there's some value in keeping them around, and users could then still emulate the behaviour of  `MCMCFollowUpSearch` by calling those functions and the standard class in a loop. Thoughts?

**Comment by Rodrigo-Tenorio** [comment]
@dbkeitel ideally the useful methods from that part will be re-implemented in a similar way to the `snr` module so they are easily access in general.

**Comment by dbkeitel** [comment]
> @dbkeitel ideally the useful methods from that part will be re-implemented in a similar way to the `snr` module so they are easily access in general.

Sounds good, but then I'd leave the deprecation until those are available. The class itself can be cleanly deprecated already in the sense that it can be reproduced by a loop over the standard class, but there's no replacement for these functions yet so seems premature to deprecate them.

**Comment by Rodrigo-Tenorio** [comment]
Sure, makes sense  :+1:

**Review by dbkeitel — APPROVED** [review]

**Pull request merged**
