### PR TITLE
Add max mismatch

### PR DESCRIPTION
**Pull request by Rodrigo-Tenorio**
Ad interface to modify the maximum-allowed mismatch by CFSv2

### CODE REVIEW

**Comment by Rodrigo-Tenorio** [comment]
I can't make it work in a semicoherent example, for some reason

**Comment by dbkeitel** [comment]
Why is the default `None` in some place and `0` in others?

**Comment by Rodrigo-Tenorio** [comment]
> Why is the default `None` in some place and `0` in others?

My mistake, I accidentally committed some debugging changes.

All should be None.

**Review by dbkeitel — CHANGES_REQUESTED** [review]
Apart from the 0->None change this already looks good, test cases included. (Codecov complains that the line in `MCMCGlitchSearch` is not covered, but let's keep that for a putative "loop test cases over variant classes" general update.) Also I haven't checked carefully if any other classes should be updated, but that can be done separately if needed.

**Review by dbkeitel — APPROVED** [review]
Defaults look good now, and examples action passed: https://github.com/PyFstat/PyFstat/actions/runs/1008001453

**Pull request merged**
